#!/usr/bin/env python3

# goos: query google
# AO-2020
#
import sys

from termcolor import colored
from googlesearch import search 


def main():
	argc = len(sys.argv)
	query=""
	tld="nl"
	if argc == 1:
		print("goos \"Some Name\" <maxresults> <tld>")
		return
	else:
		query = sys.argv[1]
	maxresults=10
	if argc >= 3:
	    maxresults = int(sys.argv[2])
	if argc >= 4:
	    tld = sys.argv[3]
	print("searching", query)
	print("max: ", maxresults)
	print("tld: ", tld, "\n")
	for j in search(query, tld, maxresults,start=0,stop=None, pause=2): 
		print(colored(j, 'blue')) 
		print('________')

if __name__ == "__main__":
	main()
